name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: "laravel"
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.2'

      - uses: actions/checkout@v4

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --optimize-autoloader

      - name: artisan optimize clear
        run: php artisan optimize:clear

      - name: Generate key
        run: php artisan key:generate

      - name: autoload
        run: composer dump-autoload

      - name: artisan optimize
        run: php artisan optimize

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Run Migrations 💾
        run: php artisan migrate --force -v
        env:
          DB_PORT: ${{job.services.mysql.ports['3306']}}
          DB_PASSWORD: password

      - name: Test with phpunit 🧐
        run: vendor/bin/phpunit
        env:
          DB_PORT: ${{job.services.mysql.ports['3306']}}
          DB_PASSWORD: password

      - name: Run Sensiolabs security checks 🚨
        run: |
          test -d security-checker || git clone https://github.com/sensiolabs/security-checker.git
          cd security-checker
          composer install
          php security-checker security:check ../composer.lock
