name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: "1a98h19a1sdh91a89s"
          MYSQL_DATABASE: "cglaravel"
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.2'
    - uses: actions/checkout@v4
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --optimize-autoloader
    - name: artisan optimize clear
      run: php artisan optimize:clear
    - name: Generate key
      run: php artisan key:generate
    - name: autoload
      run: composer dump-autoload
    - name: artisan optimize
      run: php artisan optimize
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Configure DB
      run: |
        echo "DB_CONNECTION=mysql" >> .env
        echo "DB_HOST=127.0.0.1" >> .env
        echo "DB_PORT=3306" >> .env
        echo "DB_DATABASE=cglaravel" >> .env
        echo "DB_USERNAME=root" >> .env
        echo "DB_PASSWORD=1a98h19a1sdh91a89s" >> .env
    - name: Run Migrations
      run: php artisan migrate
    - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
      run: php artisan test
