name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    env:
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: password
      DB_PORT: 3306

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: "laravel"
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.2'

      - uses: actions/checkout@v4


      - name: Start Mariadb
        run: |
          mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -uroot -ppassword -e 'CREATE DATABASE IF NOT EXISTS laravel;'

      - name: Verify MySQL connection
        run: |
          mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -uroot -ppassword -e "SHOW DATABASES"


      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --optimize-autoloader

      - name: artisan optimize clear
        run: php artisan optimize:clear

      - name: Generate key
        run: php artisan key:generate

      - name: autoload
        run: composer dump-autoload

      - name: artisan optimize
        run: php artisan optimize

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Run Migrations 💾
        run: php artisan migrate --force -v

      - name: Run NPM installer
        run: npm install

      - name: build Vite Assets
        run: npm run build

      - name: Test with phpunit 🧐
        run: |
          php artisan test --profile
          cat storage/logs/laravel.log

      - name: Run Sensiolabs security checks 🚨
        run: |
          test -d security-checker || git clone https://github.com/sensiolabs/security-checker.git
          cd security-checker
          composer install
          php security-checker security:check ../composer.lock
